# Generated by Django 3.2 on 2022-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('station_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('max_temp', models.FloatField(default=-9999)),
                ('min_temp', models.FloatField(default=-9999)),
                ('precipitation', models.FloatField(default=-9999)),
            ],
            options={
                'unique_together': {('station_id', 'date')},
            },
        ),
    ]
