# Generated by Django 3.2 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('station_id', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('avg_max_temp', models.FloatField(null=True)),
                ('avg_min_temp', models.FloatField(null=True)),
                ('total_precipitation', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('station_id', 'year')},
            },
        ),
    ]
